database:
  hostname: 'localhost'
  database: 'magma'
  auth:
    username: 'cats'
    password: 'kittens'
api:
  url: http://localhost:3000/api
  key: xxxxxxxxxxxx
  mock: true
redis:
  hostname: 'localhost'
  database: 0
  auth:
    enabled: false
    password: 'kittens'

none-online-message: "&aHey there! If you haven't noticed, &bThe Avicus Network &ais temporarily &6BACK OPEN&a!\n\nWe aren't currently accepting players right now, though.\nCheck out &9avicus.net &afor event times"